export const HANDSHAKE = 'HANDSHAKE';
export const RECONNECTED = 'RECONNECTED';
export const FORWARD = 'FORWARD';
export const BATCH_EVENTS = 'BATCH_EVENTS';
export const BATCH_EVENTS_FROM_WEBHOOK = 'BATCH_EVENTS_FROM_WEBHOOK';
export const UNIFIED_BATCH = 'UNIFIED_BATCH';
