export const HANDSHAKE = 'HANDSHAKE';
export const RECONNECTED = 'RECONNECTED';
export const FORWARD = 'FORWARD';
export const SINGLE_EVENT = 'SINGLE_EVENT';
export const BATCH_EVENTS = 'BATCH_EVENTS';
export const BATCH_EVENTS_FROM_WEBHOOK = 'BATCH_EVENTS_FROM_WEBHOOK';

export const CUSTOM_LIGHT_FUNCTIONS = ['toggle'];
